### ISSUE TITLE
如何解决词库里面不存在的词组之间的相似度为0的问题

### ISSUE THREAD

**Issue by woaidianqian** [ashengtx/CilinSimilarity#1]
转动设备 转动装置
>>> cs = CilinSimilarity()
>>> w1 = '转动设备'
>>> w2 = '转动装置'
>>> sim = cs.sim2016(w1, w2)
>>> print(w1, w2, '最终的相似度为', sim)
转动设备 转动装置 最终的相似度为 0
不希望是0的结果啊，不合理

**Comment by ashengtx** [comment]
这个需要自己在外部另外处理，比如拆开成{转动，设备}和{转动，装置}，然后计算两个集合之间的 相似度。
